version: '3'

services:
  react:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 4680:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
#      - ./frontend/public:/usr/src/app/public
      - ./frontend/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    stdin_open: true