version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 4680:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    stdin_open: true

  frontend-test:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - CI=true
    command: npm test
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/node_modules:/usr/src/app/node_modules
