version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 4690:5000
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 4680:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    stdin_open: true
    depends_on:
      - backend

  frontend-test:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - CI=true
    command: npm test
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/node_modules:/usr/src/app/node_modules

  mongo:
    image: mongo
    ports:
      - '27017:27017'